### PR TITLE
Allow to bypass the indexer-app archive limits on docker scan

### PR DESCRIPTION
**Pull request by hightoxicity**
Allow to bypass the indexer-app archive limits on docker scan

### CODE REVIEW

**Comment by hightoxicity** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by hightoxicity** [comment]
recheck

**Comment by sverdlov93** [comment]
Thanks for your contribution! @hightoxicity

**Comment by hightoxicity** [comment]
@sverdlov93 Thanks for your review and merge !

**Pull request merged**
