### PR TITLE
Using Agent.ToolsDirectory folder instead of Agent.WorkFolder

### PR DESCRIPTION
**Pull request by jeffrey-opdam**
#80 Updated the Agent.WorkFolder to Agent.ToolsDirectory as the Agent.WorkFolder is not available in container jobs.

### CODE REVIEW

**Comment by jeffrey-opdam** [comment]
merged

**Comment by jeffrey-opdam** [comment]
Will work on this, when I come back from my holiday.

Meantime: If you read the documentation of MSFT: https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#agent-variables

There is a Note for the Agent.WorkFolder variable:

"Note: This directory is not guaranteed to be writable by pipeline tasks (eg. when mapped into a container)"

and in our experience, this folder is not mapped to the build container instance.

**Comment by d4rkd0s** [comment]
> Will work on this, when I come back from my holiday.
> 
> Meantime: If you read the documentation of MSFT: https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#agent-variables
> 
> There is a Note for the Agent.WorkFolder variable:
> 
> "Note: This directory is not guaranteed to be writable by pipeline tasks (eg. when mapped into a container)"
> 
> and in our experience, this folder is not mapped to the build container instance.

This is exactly the issue our team ran into `Error: EACCES: permission denied` on linux in Azure Pipelines, we reverted to using an older version of this plugin/jfrog until this is fixed.

**Comment by rcsilva83** [comment]
Same problem here. I had to run "sudo chmod 777 /__w/" as a workaround.

Is there any estimates about when will this fix be released?

**Comment by rcsilva83** [comment]
>     1. Can you please elaborate about the use case causing this issue? How do you run the Artifactory tasks inside docker? Shouldn't the 'Agent.WorkFolder' directory also be mounted?

I'm on Azure DevOps Server 2019 (on premise) and this is how it created my build container:

##[command]/bin/docker create --name xxx --label bf0b85 --network vsts_network_56b688da40424778a129ff1959fdfd30  -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/opt/vsts-agent1/_work/1":"/__w/1" -v "/opt/vsts-agent1/_work/_temp":"/__w/_temp" -v "/opt/vsts-agent1/_work/_tool":"/__t" -v "/opt/vsts-agent1/_work/_tasks":"/__w/_tasks" -v "/opt/vsts-agent1/externals":"/__a/externals":ro -v "/opt/vsts-agent1/_work/.taskkey":"/__w/.taskkey" myimage:xxx "/__a/externals/node/bin/node" -e "setInterval(function(){}, 24 * 60 * 60 * 1000);"

So, the "Agent.WorkFolder" wasn't mounted

**Comment by eyalbe4** [comment]
@jeffrey-opdam - 
@barbelity is attempting to resolve this issue in https://github.com/jfrog/artifactory-vsts-extension/pull/124

**Comment by barbelity** [comment]
@jeffrey-opdam @rcsilva83 @d4rkd0s 
We have release version 1.8.2 of the plugin, including a fix for this issue #125 .
Now, JFrog CLI is downloaded to the $(Agent.ToolsDirectory), which should solve the issue in container jobs.
Your feedback for that is highly appreciated!

I am closing this PR.

**Pull request closed without merging**
